<?xml version="1.0" encoding="utf-8"?>
<WL5G3N2:definitions xmlns:WL5G3N1="http://xmlns.oracle.com/pcbpel/adapter/apps/OsbMedicineInfoImport/OsbMedicineInfoImport/EBS_ITF_ImportMedicineInfo" xmlns:WL5G3N3="http://xmlns.oracle.com/pcbpel/adapter/db/sp/EBS_ITF_ImportMedicineInfo" xmlns:WL5G3N0="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" name="EBS_ITF_ImportMedicineInfo" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/apps/OsbMedicineInfoImport/OsbMedicineInfoImport/EBS_ITF_ImportMedicineInfo" xmlns:WL5G3N2="http://schemas.xmlsoap.org/wsdl/">
  <WL5G3N0:partnerLinkType name="EBS_ITF_ImportMedicineInfo_plt">
    <WL5G3N0:role name="EBS_ITF_ImportMedicineInfo_role">
      <WL5G3N0:portType name="WL5G3N1:EBS_ITF_ImportMedicineInfo_ptt" />
    </WL5G3N0:role>
  </WL5G3N0:partnerLinkType>
  <WL5G3N2:types>
    <schema xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/EBS_ITF_ImportMedicineInfo" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/apps/OsbMedicineInfoImport/OsbMedicineInfoImport/EBS_ITF_ImportMedicineInfo" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://www.w3.org/2001/XMLSchema">
      <import schemaLocation="http://172.16.8.169:8011/SinoPharmSOA8058/ProxyServices/EBS_ITF_ImportMedicineInfo_apps_PS?SCHEMA%2FSinoPharmSOA8058%2FResources%2Fjca%2Fxsd%2FEBS_ITF_ImportMedicineInfo_sp" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/EBS_ITF_ImportMedicineInfo" />
    </schema>
  </WL5G3N2:types>
  <WL5G3N2:message name="args_in_msg">
    <WL5G3N2:part name="InputParameters" element="WL5G3N3:InputParameters" />
  </WL5G3N2:message>
  <WL5G3N2:message name="args_out_msg">
    <WL5G3N2:part name="OutputParameters" element="WL5G3N3:OutputParameters" />
  </WL5G3N2:message>
  <WL5G3N2:portType name="EBS_ITF_ImportMedicineInfo_ptt">
    <WL5G3N2:operation name="EBS_ITF_ImportMedicineInfo">
      <WL5G3N2:input message="WL5G3N1:args_in_msg" />
      <WL5G3N2:output message="WL5G3N1:args_out_msg" />
    </WL5G3N2:operation>
  </WL5G3N2:portType>
</WL5G3N2:definitions>